import type { Lesson } from "./curriculum";

type Mastery = NonNullable<Lesson["mastery"]>;
const m = (
  title1: string,
  body1: string,
  title2: string,
  body2: string,
  claim: string,
  correction: string,
  question: string,
  answer: string,
): Mastery => ({
  sections: [
    { title: title1, body: body1 },
    { title: title2, body: body2 },
  ],
  misconception: { claim, correction },
  challenge: { question, answer },
});

export const lessonMastery: Record<string, Mastery> = {
  fundamentals: m(
    "The abstraction boundary",
    "Applications depend on a logical interface, while the DBMS maps that interface to storage. This separation is why adding an index can speed a query without changing its SQL. The cost is an extra software layer that requires configuration, monitoring, and backups.",
    "Choosing a system",
    "A small static list may not need a database. Once multiple users edit related facts, constraints, transactions, and recovery become more important than raw file simplicity. A browser SQLite database is useful for learning these rules, but its local storage is not a substitute for a shared production server.",
    "A DBMS makes every query fast and every data model correct.",
    "A DBMS provides tools and guarantees, but schema design, query formulation, indexes, and operational settings still determine correctness and performance.",
    "A team replaces CSV files with a DBMS but stores all entities in one text column. Which benefits remain, and which are lost?",
    "Transactions and file-level recovery may improve, but useful constraints, joins, and targeted indexes are largely lost because the facts are not modeled as typed relational attributes.",
  ),
  "relational-model": m(
    "Theory versus SQL implementation",
    "Classical relational algebra treats a relation as a set, so duplicate tuples are absent and row order has no meaning. SQL uses bag-like results by default and permits NULL. DISTINCT and ORDER BY are explicit bridges from SQL behavior toward set and ordered presentation semantics.",
    "Domain and identity",
    "A column domain restricts permitted kinds of value. A stable key gives identity independent of mutable descriptive data. Names, addresses, and prices can change or repeat; IDs should not acquire a new meaning just because their visible attributes change.",
    "A table always has a meaningful row order.",
    "Storage order and display order can change after inserts, vacuuming, or plan changes. Only ORDER BY defines requested result order.",
    "Why is customer name usually a poor foreign key from orders?",
    "Names can repeat and change. A stable unique customer_id provides a reliable reference while the name remains an ordinary mutable attribute.",
  ),
  "keys-constraints": m(
    "Composite identity",
    "A composite primary key is useful when identity arises from a combination, such as one product per order. A referencing foreign key must use a compatible set of columns. Declaring each component independently does not enforce the same relationship as one composite foreign key.",
    "Rules across time",
    "Constraints protect each committed database state, but some business rules require transactions as well. For example, a foreign key can ensure an order references a customer; it does not by itself guarantee that a complete order has at least one item at the instant the workflow finishes.",
    "UNIQUE and PRIMARY KEY are interchangeable.",
    "A table has one chosen primary key that is non-null by definition. Other candidate keys can be UNIQUE, and SQL's treatment of NULL in UNIQUE columns varies by dialect.",
    "An order_items table declares UNIQUE(order_id) and UNIQUE(product_id). Does that model an order containing many products?",
    "No. Each unique constraint separately permits only one item per order and one order per product. A composite key or unique constraint on (order_id, product_id) expresses the intended pair uniqueness.",
  ),
  "er-modeling": m(
    "Relationship attributes",
    "A property like quantity cannot be assigned to Product alone or Order alone: it depends on the particular Order–Product relationship. This is evidence that the relationship needs its own associative entity when implemented relationally.",
    "Modeling optionality",
    "Ask both directions of every relationship: how many B instances can one A have, and how many A instances can one B have? Then ask whether zero is allowed on each side. A diagram that shows only a 1:N maximum still leaves crucial constraints unspecified.",
    "Every noun in a requirement must become its own table.",
    "Some nouns are attributes, some are entities, and some describe a relationship or event. The decision depends on identity, lifecycle, and independent facts.",
    "A customer may place many orders, but every order must have one customer. Which side is optional?",
    "Customer participation is optional (zero orders allowed); order participation is mandatory (one customer required).",
  ),
  "sql-basics": m(
    "Logical query sequence",
    "A useful mental order is FROM, WHERE, GROUP BY, HAVING, SELECT, DISTINCT, ORDER BY, then LIMIT. Engines can physically execute operations differently when the result is equivalent. This explains why a SELECT alias is not generally available in WHERE.",
    "Result contracts",
    "A production query should state the columns and ordering its caller expects. SELECT * couples the caller to every schema addition; LIMIT without ORDER BY returns an arbitrary subset. Explicit aliases help distinguish same-named columns from joins.",
    "LIMIT 5 means the first five inserted rows.",
    "Without ORDER BY, there is no defined first row. A different index or plan may produce a different five rows.",
    "Why might SELECT price * quantity AS total FROM items WHERE total > 100 fail in many SQL dialects?",
    "WHERE is logically evaluated before SELECT creates the alias. Repeat the expression in WHERE or use a subquery/CTE that exposes total to an outer query.",
  ),
  "filter-sort": m(
    "Boolean precedence and UNKNOWN",
    "NOT binds more tightly than AND, which binds more tightly than OR in SQL. Parentheses make intent clear. NULL comparisons introduce UNKNOWN: NOT UNKNOWN remains UNKNOWN, and WHERE excludes it. IS NULL and IS NOT NULL are the correct missing-value predicates.",
    "Stable pages of results",
    "OFFSET pagination can skip changing data and grow costly on high page numbers. Keyset pagination compares a stable ordered key pair, such as (order_date, order_id), to the last seen row. The tie-breaker makes the sequence deterministic.",
    "A condition `column <> 5` includes NULL values.",
    "NULL <> 5 is UNKNOWN, not TRUE; add OR column IS NULL if those rows are intended.",
    "A report sorts only by order_date, and several orders share the date. Why can page boundaries shift?",
    "The tied rows have no defined relative order. Add a unique tie-breaker such as order_id to ORDER BY.",
  ),
  joins: m(
    "Outer-join predicate placement",
    "For a LEFT JOIN, put the matching rule in ON. A filter on the right table in WHERE runs after NULL-extension and can remove unmatched left rows. Move conditions carefully: ON and WHERE are not interchangeable for outer joins.",
    "Multiplicity is arithmetic",
    "If one customer has three orders and each order has two items, joining all three relations yields six rows for that customer. SUM(customer-level value) over the joined result may count the same value six times. Aggregate at the correct grain before joining.",
    "An unexpected number of rows always means duplicate data.",
    "A one-to-many or many-to-many join naturally multiplies parent rows. Diagnose join keys and the desired result grain before adding DISTINCT.",
    "Why does `LEFT JOIN orders ... WHERE orders.status = 'Shipped'` omit customers with no orders?",
    "The NULL-extended status fails the WHERE test, so those rows are discarded. Put the status restriction in ON when unmatched customers must remain.",
  ),
  grouping: m(
    "The grain of a result",
    "The GROUP BY columns define one output row per distinct grouping key. A measure such as total sales must be calculated at that grain. Mixing a customer-level value with an order-item-level join can duplicate the value before SUM sees it.",
    "Aggregate and NULL details",
    "COUNT(*) includes rows even when columns are NULL. COUNT(email) counts non-null email values. SUM ignores NULL inputs and may return NULL if no non-null value exists, while COUNT returns zero. Use COALESCE only when zero is the correct interpretation.",
    "HAVING is just a slower spelling of WHERE.",
    "WHERE filters individual rows before groups form; HAVING filters aggregate groups. They are not interchangeable when an aggregate is involved.",
    "A customer has two orders and each has three items. What can go wrong with COUNT(*) after joining customers, orders, and items?",
    "It returns six joined item rows, not two orders. Count distinct order IDs or aggregate orders at the intended grain before joining items.",
  ),
  "subqueries-ctes": m(
    "Correlated existence",
    "EXISTS asks whether at least one row satisfies a predicate tied to the current outer row. It does not need to return data from the subquery, and SELECT 1 communicates that intent. Double NOT EXISTS is a common way to express a universal 'every required item' condition.",
    "Materialization is not guaranteed",
    "A CTE is a named query block, not always a temporary stored table. Depending on the engine and query, it may be inlined or materialized. Readability is its reliable benefit; performance should be tested from the actual plan.",
    "NOT IN and NOT EXISTS always behave identically.",
    "If the NOT IN subquery includes NULL, the result can become UNKNOWN for all tested values. A correctly correlated NOT EXISTS avoids that particular trap.",
    "Why might `id NOT IN (SELECT id FROM blocked)` return no rows when blocked contains NULL?",
    "Comparisons against NULL are UNKNOWN, so the overall NOT IN predicate may never be TRUE. Filter NULL from the subquery or use a correlated NOT EXISTS.",
  ),
  "set-operations": m(
    "Whole-row equality",
    "UNION deduplicates complete output rows. If you select both customer_id and status, two rows with the same customer_id but different status remain distinct. INTERSECT and EXCEPT likewise compare the full compatible row shape.",
    "Operator cost and interpretation",
    "UNION often needs sorting or hashing to remove duplicates. UNION ALL can stream both inputs when duplicates are acceptable. Choose by meaning first, then consider cost. Ensure corresponding columns represent the same domain, not merely compatible types.",
    "UNION matches customers to orders by key.",
    "UNION appends compatible rows vertically. JOIN matches related rows horizontally through a predicate.",
    "Two queries each return (id, status). A shared id has different statuses. Will UNION keep one or two rows?",
    "Two. Deduplication compares the entire (id, status) tuple, not id alone.",
  ),
  views: m(
    "View expansion and security",
    "A standard view is usually evaluated through its defining query, so base-table indexes and predicates still matter. Exposing fewer columns through a view can support a privilege design, but the user's actual grants and the engine's security model determine whether data is protected.",
    "Materialized alternatives",
    "A materialized view stores a result and can speed repeated expensive reads, but it becomes stale until refreshed. Standard views trade storage for fresh evaluation. The choice depends on latency, update frequency, and acceptable staleness.",
    "Creating a view automatically caches the result.",
    "A standard view stores a query definition, not a reusable data copy. Repeated reads may repeat expensive underlying work.",
    "A report view joins orders and items, then sums amounts. Does querying it eliminate the join cost?",
    "No. A standard view still evaluates its defining logic unless an optimizer can simplify it; use a measured materialized strategy if cached summaries are required.",
  ),
  indexes: m(
    "Leftmost-prefix reasoning",
    "A composite B+ tree on (customer_id, order_date) groups entries by customer first and date second. Filtering only by date cannot generally jump to one contiguous range of that index. Filtering by customer and date can use the ordering much more directly.",
    "Covering and clustering",
    "An index is covering for a query when it contains all columns needed by that query. A clustered layout keeps related rows near one another, reducing data-page reads for ranges; an unclustered index may require scattered lookups. These distinctions explain why equal key counts can have different costs.",
    "Any index makes every query faster.",
    "Low-selectivity reads may favor scans, while each index adds storage and maintenance to writes.",
    "An index is on (customer_id, order_date). Which predicate is more naturally supported: customer_id = 7 or order_date = '2024-01-01' alone?",
    "customer_id = 7, because customer_id is the leading index key. The date-only predicate does not identify one contiguous leading-key range.",
  ),
  "transactions-acid": m(
    "Consistency is not automatic business correctness",
    "Consistency means a transaction starts and ends in states satisfying enforced rules. If the schema never declares 'balance must be nonnegative,' the DBMS cannot invent that rule. The transaction must include the right checks and writes, and concurrent checks need adequate isolation.",
    "Commit and durability",
    "COMMIT is the point at which a transaction's effects become committed. Durable engines use mechanisms such as logs and page flushing to survive crashes. A client-side browser database teaches the SQL boundary but should not be treated as having the operational durability of a managed server.",
    "ACID means transactions can be written without thinking about concurrency.",
    "Isolation level and operation order still matter. Two individually atomic transfers can interfere if each reads a stale balance.",
    "A transfer debits A, commits, then credits B in a second transaction. Which ACID property cannot protect the combined business action?",
    "Atomicity applies to each transaction separately. Split commits mean the debit can persist without the credit; both writes must share one transaction.",
  ),
  normalization: m(
    "Candidate keys drive normal forms",
    "Normal-form tests require all relevant functional dependencies and candidate keys, not just the declared primary key. For 3NF, a nontrivial FD X → A is allowed when X is a superkey or A is prime (part of some candidate key). BCNF removes the prime-attribute exception.",
    "Lossless versus dependency preserving",
    "A BCNF decomposition can be lossless yet make an original FD impossible to check inside either resulting relation alone. 3NF synthesis is often used when preserving dependencies is important. A design decision must consider both properties and the application's update workload.",
    "A schema is normalized because every table has a primary key.",
    "All useful tables need identifiers, but normal forms depend on dependencies among attributes. A table can have a primary key and still repeat unrelated facts.",
    "R(A,B,C) has FDs A → B and B → C, with A the only candidate key. Why is C problematic for 3NF?",
    "B → C has a non-superkey determinant B and non-prime dependent C, producing a transitive dependency and a 3NF violation.",
  ),
  "procedures-triggers": m(
    "Nested effects and rollback",
    "A trigger's write can cause another trigger to fire, depending on the engine and configuration. Trace the entire chain and transaction boundary. A failure inside the chain may abort the original statement, but exact error and recursion behavior is dialect-specific.",
    "Set-based before procedural",
    "Many row-by-row tasks can be expressed as one UPDATE, INSERT ... SELECT, or constraint. This can be easier to optimize and reason about than a cursor loop. Use procedural database logic when sequencing, validation, or encapsulation truly requires it.",
    "A trigger is the best way to implement every integrity rule.",
    "Declarative NOT NULL, UNIQUE, CHECK, and foreign keys are clearer and typically easier for the DBMS to enforce. Reserve triggers for rules they cannot express well.",
    "An order INSERT fires an audit trigger, and the audit write fails. Should the order commit?",
    "In a transactional trigger design, the original statement/transaction should fail rather than leave an unaudited committed order; verify exact engine semantics.",
  ),
  "query-plans": m(
    "Estimated cardinality compounds",
    "If a filter is predicted to return 10 rows but actually returns 10,000, every downstream join cost estimate can be wrong. The optimizer may choose nested loops instead of hashing or put a large input on the wrong side of a join. Statistics and correlated columns are central to this problem.",
    "Evidence from plans",
    "EXPLAIN identifies operators and access paths. When available, compare estimated rows with actual rows and look for large gaps. A scan is not inherently bad: reading all pages sequentially can beat thousands of random index lookups when most rows qualify.",
    "An index seek is always preferable to a table scan.",
    "When a predicate returns a large fraction of a table, the seek plus many row fetches may read more pages than a scan.",
    "A plan estimates 5 rows after a filter but produces 50,000. What should be investigated first?",
    "Inspect the filter's statistics, selectivity assumptions, and data correlation; the bad estimate may explain poor downstream join choices.",
  ),
  concurrency: m(
    "Read and write anomalies differ",
    "A dirty read observes uncommitted work; a lost update overwrites another write; write skew can occur when two transactions read a shared condition and update different rows. Preventing dirty reads alone does not guarantee serializable business rules.",
    "Isolation varies by engine",
    "Names such as READ COMMITTED and REPEATABLE READ are useful categories, but exact handling of phantoms, snapshots, and write conflicts differs among DBMSs. The browser SQLite example cannot demonstrate every multi-session behavior; use the schedule simulator to reason about the abstract rules.",
    "If two transactions write different rows, they cannot violate a shared rule.",
    "Write skew can violate a constraint across rows even when the writes do not overlap, if both transactions make decisions from the same stale snapshot.",
    "Two doctors each see the other on call and independently go off call. What anomaly can leave no doctor on call?",
    "Write skew: each transaction reads a shared condition, then changes a different row. Serializable isolation or an explicit coordination rule is needed.",
  ),
  security: m(
    "Parameters have a boundary",
    "Bound parameters protect values, not arbitrary SQL identifiers such as table names or ORDER BY column tokens. For dynamic identifiers, choose from a fixed allowlist and construct only the approved token. Never put user-supplied SQL fragments directly into a query.",
    "Browser-local threat model",
    "This app executes practice SQL in the user's browser. Local isolation and read-only exercises are learning safeguards, not server-side authorization. Imported data may remain in browser storage or exports, so students should avoid loading sensitive production datasets.",
    "Replacing quotes is as safe as bound parameters.",
    "Manual escaping can miss dialect rules, encodings, and context. Parameters keep syntax and values separate by design.",
    "A user chooses a sort column. Can `ORDER BY ?` bind the column name?",
    "Usually no: a parameter represents a value, not an identifier. Map the user's choice to a fixed allowlist of approved column names.",
  ),
  "backup-recovery": m(
    "Recovery objectives",
    "Recovery point objective (RPO) is the maximum acceptable lost work; recovery time objective (RTO) is the acceptable time to restore service. A weekly backup may be perfectly usable but fail a one-hour RPO. A complicated restore may fail a short RTO.",
    "A restore rehearsal",
    "Test more than whether a file opens. Verify schema, row counts, constraints, key queries, and the ability to resume normal writes. Store backup generations separately from the active database so one local failure or accidental overwrite cannot destroy both.",
    "Replication is a backup because there are two copies.",
    "A replica follows current changes, including corruption and accidental deletes. Historical backups retain earlier recoverable states.",
    "Backups run nightly at midnight. A failure happens at 23:50 with no log replay. What is the worst-case RPO?",
    "Almost 24 hours of work since the previous midnight backup may be lost.",
  ),
  distributed: m(
    "Lag and read-after-write",
    "An asynchronous replica can serve stale data just after the primary accepts a write. A user who updates a profile and immediately reads from a lagging replica might see the old value. Routing that read to the primary or using a consistency mechanism changes the latency/availability tradeoff.",
    "Cross-shard cost",
    "A query scoped by shard key can route to one shard. A query lacking the key may fan out to every shard and merge results. Sharding also makes uniqueness and transactions spanning shards harder to coordinate, so partitioning should follow measured bottlenecks.",
    "Sharding always improves every query.",
    "Single-shard operations can scale well, while fan-out queries and cross-shard joins can become slower and more complex.",
    "A database is sharded by customer_id. Why is a lookup by order_date across all customers expensive?",
    "order_date does not identify one shard, so the query may need to scan or ask every shard and merge their results.",
  ),
  nosql: m(
    "Model families, not slogans",
    "A document store and a graph store may both be called NoSQL, but one centers nested aggregate reads and the other centers connected traversals. Their transaction, index, and consistency guarantees are product-specific. Evaluate a concrete product against the required workload.",
    "Duplicated data needs a policy",
    "Denormalizing into documents can make reads convenient, but a repeated customer name across thousands of orders becomes hard to keep synchronized. Decide which fields are snapshots (historical at purchase time) and which should remain references to current shared data.",
    "NoSQL means no schema or no transactions.",
    "Many non-relational systems support schema validation and transactions. The label describes a family of data models, not absence of rules.",
    "When might a graph model fit better than a document model?",
    "When the primary queries repeatedly traverse variable-length relationships, such as social connections or dependency paths, rather than fetching bounded aggregates.",
  ),
  "mongodb-documents": m(
    "Aggregate boundaries",
    "Embedding is strongest when child data is bounded, owned by one parent, and frequently read with it. References suit independently changing or shared entities. An order's purchase-time address may be an intentional snapshot, while the customer's current address remains separate.",
    "Indexes follow query shape",
    "Nested fields and array contents can be queried, but the index must match the frequent filter and sort shape. More indexes have write and storage costs. A flexible document shape does not eliminate the need for field naming and validation discipline.",
    "Every one-to-many relationship should be embedded.",
    "An unbounded history can grow indefinitely and create oversized or frequently rewritten documents. Reference such collections instead.",
    "Should a customer document embed every order the customer will ever place?",
    "Usually not: order history is unbounded and changes independently. Separate orders with a customer reference and an appropriate index are safer.",
  ),
  "mongodb-aggregation": m(
    "Shape changes are observable",
    "After $group, the stream no longer has the original document shape unless fields are explicitly carried forward. A later $sort or $project must refer to the grouped output fields. Sketch one example document after each stage to catch wrong assumptions.",
    "When an index helps",
    "An early selective $match may use an index; a suitable sort may also use index order. A $group over most documents still has to process the qualifying stream. Treat the browser visualization as a conceptual pipeline, not as a live MongoDB server or benchmark.",
    "Pipeline stages can always be rearranged without changing results.",
    "Moving $project before a stage that needs a removed field, or moving $match across a shape-changing $group, can change meaning or make the pipeline invalid.",
    "A pipeline groups by status, then sorts by order_date. Why might the sort fail?",
    "After grouping, individual order_date fields are not available unless the group computed or retained a date value to sort on.",
  ),
  "case-study": m(
    "A schema's grain",
    "orders stores one transaction header; order_items stores one purchased product within that transaction; products stores current catalog facts. Mixing these grains leads to double-counted totals and overwritten history. Decide the grain of every table and report before choosing aggregates.",
    "Constraints versus workflow",
    "Foreign keys can reject missing customers and products. A check can reject negative quantities. Ensuring an order has at least one item and that inventory decreases safely may need a transaction and application or database-side workflow, not just one row-level constraint.",
    "Storing total_amount removes the need to reason about order items.",
    "A cached total must be kept consistent with item quantities, prices, discounts, and taxes. Derive or validate it against the item facts.",
    "Why retain unit_price on order_items after products.price changes?",
    "unit_price is the historical price for that particular purchase; products.price represents the current catalog offer.",
  ),
  "dbms-architecture": m(
    "Mappings are contracts",
    "The external–conceptual mapping connects a user's view to the global logical schema; the conceptual–internal mapping connects that schema to storage. An index changes the internal level. Splitting one logical table affects the conceptual level and may require redefining views to preserve external contracts.",
    "Independence has limits",
    "Physical independence is relatively common because file organization is hidden from SQL. Logical independence is harder: a changed meaning, key, or relationship cannot always be concealed by a compatible view. Distinguish structural compatibility from genuinely preserved semantics.",
    "Any conceptual schema change can be hidden by a view.",
    "Some changes alter meaning or remove information. A view cannot reconstruct facts that the new schema no longer represents.",
    "A table column is removed because the data is no longer collected. Can an old view always keep returning it faithfully?",
    "No. It may provide a constant or NULL for compatibility, but it cannot recover the original information or preserve the old semantics.",
  ),
  "eer-design": m(
    "Subtype constraints",
    "A specialization can be disjoint or overlapping, and total or partial. Disjoint says an instance belongs to at most one subtype; total says every supertype instance belongs to at least one. The two dimensions are independent and must be declared from requirements.",
    "Weak entity existence",
    "A weak entity depends on an owner for identification and typically existence. If an order is deleted, its lines cannot remain valid without another owner. The identifying relationship and total participation express that dependency before SQL foreign keys are chosen.",
    "A weak entity is simply a table with few columns.",
    "Weakness is about identity and existence dependence on an owner, not size or number of attributes.",
    "Employees can be both managers and engineers, but some are neither. Is the specialization overlapping or disjoint, total or partial?",
    "Overlapping and partial: subtype membership can overlap, and not every Employee must join a subtype.",
  ),
  "er-mapping": m(
    "One-to-one placement",
    "A 1:1 relationship can be mapped with a foreign key on either side plus UNIQUE. Choose the side with total participation or the more natural lifecycle to minimize NULLs. If both sides are optional, a separate relationship relation may communicate the association more cleanly.",
    "Minimum constraints can be hard",
    "A NOT NULL foreign key makes the referencing row participate, but it does not guarantee every parent has a child. Enforcing 'every order has at least one item' may require transaction-level workflow, deferred checks, or additional logic depending on the engine.",
    "A foreign key alone enforces a one-to-one relationship.",
    "It only ensures the target exists. Without UNIQUE on the referencing column, multiple rows may point to the same target.",
    "How can Passport(person_id) reference Person while allowing at most one passport per person?",
    "Declare person_id as a foreign key and UNIQUE (or the passport table's primary key) so the same person_id cannot occur twice.",
  ),
  "relational-algebra": m(
    "Expression-tree equivalence",
    "Selection and projection can often be pushed toward source relations to shrink intermediate results, as long as needed join columns are retained. This is an algebraic reason query optimizers rewrite SQL before choosing physical operators.",
    "Calculus and safety",
    "Tuple and domain calculus state which tuples or values satisfy predicates rather than giving an operation sequence. A safe expression ranges over database-derived values so its result is finite and meaningful. Universal questions can be expressed using negated existence of a counterexample.",
    "Projection in relational algebra preserves duplicates like ordinary SQL SELECT.",
    "Classical algebra returns a set and removes duplicates; ordinary SQL SELECT is bag-like unless DISTINCT is used.",
    "How would you read 'customers who bought every product in Required' as a counterexample test?",
    "Select customers for whom no Required product exists that the customer has not bought—logically, NOT EXISTS a missing required purchase.",
  ),
  "functional-dependencies": m(
    "Closure as an algorithm",
    "Start with X⁺ = X. Scan each FD Y → Z; whenever Y is already contained in the closure, add Z. Repeat until no attribute is added. This fixed point is independent of rule application order, though some orders reach it faster.",
    "Minimal cover nuance",
    "To minimize FDs, first split multi-attribute right sides. Then test each left-side attribute for extraneousness using closure under the other effective rules; finally test whether an FD is redundant. A minimal cover is equivalent to the original set, not necessarily unique in textual form.",
    "A sample table proving X → Y makes the dependency a permanent rule.",
    "Sample data can accidentally satisfy an FD. An FD should come from domain semantics and hold for every valid instance.",
    "For R(A,B,C,D,E), with A → B, B → C, CD → E, is AD a candidate key?",
    "AD⁺ = ABCDE, so AD is a superkey. A⁺ lacks D and E, while D⁺ is only D; neither proper one-attribute subset is a superkey, so AD is a candidate key.",
  ),
  "normalization-proofs": m(
    "Spurious-tuple witness",
    "A lossy decomposition may look harmless until two source rows share the join attribute. R(A,B,C) rows (1,x,p) and (2,x,q), split into (A,B) and (B,C), rejoin to produce false rows (1,x,q) and (2,x,p). A concrete witness helps verify the formal lossless condition.",
    "Beyond 4NF",
    "4NF addresses nontrivial multivalued dependencies whose determinant is not a superkey. 5NF deals with join dependencies where a relation can be reconstructed from several projections even though the redundancy is not captured by a simpler FD or MVD. These higher forms are rarer but part of the theory syllabus.",
    "Every decomposition that removes repeated values is lossless.",
    "Splitting on non-key shared attributes can generate spurious combinations when the parts are joined back.",
    "R(A,B,C) has rows (1,x,p) and (2,x,q). What false rows arise after decomposing into (A,B) and (B,C) and joining?",
    "The join also produces (1,x,q) and (2,x,p), proving this instance is not reconstructed exactly.",
  ),
  "transaction-schedules": m(
    "Conflict versus view equivalence",
    "Conflict serializability is a sufficient, efficiently testable condition based on swapping nonconflicting operations. Some schedules are view-serializable but not conflict-serializable, especially with blind writes. The precedence graph test establishes the stricter conflict property, not every possible notion of equivalent outcome.",
    "Commit order and recovery",
    "Serializability asks whether concurrent operations behave like a serial order. Recoverability asks whether a transaction commits only after transactions whose values it read have committed. A schedule can pass one test and fail the other; both matter.",
    "An acyclic conflict graph proves the schedule is recoverable.",
    "Acyclicity proves conflict serializability. Recoverability requires checking read-from dependencies and commit order separately.",
    "T2 reads a value written by T1, then T2 commits before T1. Even if the conflict graph is acyclic, what is wrong?",
    "The schedule is non-recoverable: if T1 aborts, T2 has already committed based on invalid data.",
  ),
  "concurrency-protocols": m(
    "Basic versus strict 2PL",
    "Basic two-phase locking grows a lock set and then shrinks it, guaranteeing conflict serializability but potentially permitting cascading aborts. Strict 2PL retains exclusive locks through commit or abort, preventing another transaction from reading or overwriting an uncommitted write.",
    "MVCC is not a single isolation level",
    "Version storage lets reads observe a snapshot without blocking every writer. The snapshot rules and write-conflict handling determine whether anomalies such as write skew remain. Serializable MVCC implementations need extra detection or constraints beyond simply storing old versions.",
    "Two-phase locking means exactly two locks.",
    "The two phases are growing and shrinking; any number of locks may be acquired subject to that discipline.",
    "T1 releases its first lock, then later acquires another. Does it follow basic 2PL?",
    "No. Once the shrinking phase begins by releasing a lock, basic 2PL prohibits acquiring new locks.",
  ),
  "physical-storage": m(
    "Slotted pages and record IDs",
    "A slotted page stores a slot directory so records can move within the page while a logical page-and-slot record identifier remains usable. Variable-length rows require free-space management. The buffer pool maps disk pages into memory frames and controls when dirty pages are written back.",
    "Cost is access-pattern dependent",
    "A sequential scan reads each data page once. An unclustered secondary-index lookup may read one index path plus a data page per matching row, though cache hits can reduce actual I/O. A clustered range can visit far fewer distinct pages for the same number of matches.",
    "Finding 100 rows always costs 100 disk reads.",
    "Rows may share pages or already be cached; conversely, an index path and random access can add reads. Page layout and buffer state matter.",
    "A table has 103 records and 10 fit per page. How many data pages must an uncached full scan read?",
    "ceil(103/10) = 11 pages, ignoring headers and variable record sizes.",
  ),
  "index-internals": m(
    "Separator propagation",
    "A B+ tree leaf split partitions sorted keys and inserts a separator into its parent. If the parent is full, the split can propagate upward; splitting the root increases tree height. Balanced height keeps equality and range entry lookups logarithmic in the number of indexed entries.",
    "Why hash differs",
    "Hashing maps keys to buckets for equality access. A predicate such as price BETWEEN 20 AND 50 needs ordered neighboring keys, which a hash index does not provide naturally. B+ tree linked leaves support scanning that range after locating its first leaf.",
    "B+ tree internal nodes store every table row.",
    "Internal nodes guide the search with separators; data records or row references live at leaves, depending on the storage organization.",
    "Why can inserting one key increase the height of a B+ tree?",
    "If a full leaf splits and separator insertions cascade through full ancestors, the root splits and a new root level is created.",
  ),
  "sql-deep-dive": m(
    "UNKNOWN propagates",
    "SQL WHERE accepts only TRUE. For example, `NOT (email = 'a@x')` remains UNKNOWN when email is NULL. The safe way to include missing emails is an explicit `OR email IS NULL`. Similar reasoning explains NOT IN surprises.",
    "Portable versus dialect-specific SQL",
    "Concepts such as constraints, correlated subqueries, and transaction boundaries generalize, but syntax and behavior of procedures, assertions, date functions, and UPDATE variants differ. The browser runs SQLite, so examples using another dialect should be labeled conceptual rather than presented as executable there.",
    "`NULL = NULL` is TRUE because both sides are missing.",
    "The comparison is UNKNOWN. Use IS NULL to test for a missing value, and use an engine's null-safe equality only when that dialect explicitly provides it.",
    "If a subquery returns values (1, NULL), what is the risk of `WHERE id NOT IN (...)`?",
    "For IDs other than 1, comparison with NULL can make the predicate UNKNOWN, so rows expected as 'not blocked' may not appear.",
  ),
  "query-costs": m(
    "Explicit model assumptions",
    "A simple page nested loop with B outer pages and C inner pages costs about B + B×C page reads when every inner page is rescanned. An in-memory hash join has a rough input scan cost B + C, but building and probing take CPU and spilling adds I/O. These formulas are teaching models, not universal optimizer equations.",
    "Selectivity changes the winner",
    "A selective outer input with an index on the inner join key can make indexed nested loops cheap: each outer row performs a targeted probe. A large equality join without useful indexes often favors hashing. Sorted inputs may make merge joining attractive.",
    "Hash join always beats nested loop because B+C is smaller than B+B×C.",
    "The comparison assumes an uncached simple loop and an in-memory hash table. Index probes, tiny inputs, caching, and hash spills can reverse the result.",
    "An outer relation is 20 pages and an inner is 80. Estimate simple page nested-loop reads when the inner is scanned for each outer page.",
    "20 + 20×80 = 1,620 page reads, before caching or other optimizations.",
  ),
  "recovery-internals": m(
    "Steal and no-force",
    "A buffer manager may write a dirty uncommitted page to disk (steal) and may defer a committed page's disk write (no-force). This combination improves throughput but requires both undo of uncommitted effects and redo of committed effects during recovery. WAL provides the necessary log ordering.",
    "Checkpoints narrow work",
    "A checkpoint records a recovery reference point and relevant active state, reducing how far back recovery must analyze in common cases. It does not mean every data page is necessarily flushed or that all earlier logs can immediately be discarded. Exact checkpoint and redo rules are engine-specific.",
    "After a commit record is durable, every changed data page must already be durable.",
    "Under a no-force policy, committed pages may still be in memory; recovery redoes them from the durable log if a crash occurs.",
    "Why are both undo and redo needed with steal/no-force buffering?",
    "Steal may put uncommitted changes on disk, requiring undo; no-force may leave committed changes only in memory, requiring redo.",
  ),
  "database-programming": m(
    "Event ordering matters",
    "A BEFORE trigger can validate or transform an impending row change; an AFTER trigger reacts to the completed row event within the statement's transaction. Trigger order, recursion, and available old/new row values are dialect-specific. Draw an event timeline when multiple automatic actions interact.",
    "Cursor cost versus clarity",
    "A cursor makes per-row sequencing explicit but can cause repeated context switches and queries. A single set-based operation often handles many rows more efficiently. If a cursor is necessary, define the query, open/fetch/close lifecycle, transaction boundary, and failure handling.",
    "Procedures and cursors in this lesson run inside browser SQLite.",
    "SQLite supports triggers but not the general stored-procedure and cursor syntax of server DBMSs. Those parts are conceptual simulations here.",
    "When is one UPDATE preferable to a cursor that changes every overdue loan?",
    "When the rule can be expressed as a set predicate and calculation, one UPDATE lets the engine optimize the batch and avoids row-by-row control overhead.",
  ),
  "design-case-studies": m(
    "Validate with counterexamples",
    "After mapping a case study, deliberately try edge cases: a patient with no appointments, two appointments in the same slot, a returned loan followed by a new loan, or an account transfer that fails midway. These tests expose missing participation rules, uniqueness rules, and transaction boundaries.",
    "Traceability from rule to enforcement",
    "For each requirement, record where it is represented: entity, attribute, foreign key, UNIQUE/CHECK constraint, transaction, or application workflow. If a rule has no enforcement location, the schema diagram alone does not satisfy it. Then test representative queries and access paths before choosing indexes.",
    "A realistic case study is finished once the ER diagram looks plausible.",
    "It must map to relations, survive edge-case data, enforce key rules, support required queries, and handle update workflows and failures.",
    "A library permits repeated loans of the same copy over time. Why is (member_id, copy_id) alone a poor Loan primary key?",
    "It would prohibit the same member borrowing that copy again. Add an event identifier or a time component that uniquely distinguishes separate loans.",
  ),
};
